import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./ui/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-black`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
